#define SCREEN_WIDTH 1024
#define SCREEN_HEIGHT 768
#define SCREEN_TITLE "Owaria!"
#define TARGET_FPS 60.0f
#define TARGET_UPS 60.0f
#define TARGET_FPS_TIME 1.0f / TARGET_FPS
#define TARGET_UPS_TIME 1.0f / TARGET_UPS
#define V_SYNC false
#define BOX2D_SCALE 30.0f
#define BOX2D_VELOCITY_ITERATIONS 8
#define BOX2D_POSITION_ITERATIONS 3
#define ENGINE_PI 3.14f


#define PLAYER_SPEED 7;
#define PLAYER_JUMP_SPEED 10;
#define MAP_FRICTION 3
#define PLAYER_DENSITY 10
#define PLAYER_FRICTION 3

#define FOOT_SENSOR 1